const { EntitySchema } = require("typeorm");

const ClimateDatabaseEntity = new EntitySchema({
  name: "ClimateDatabase",
  tableName: "ClimateDatabase",
  columns: {
    ID: {
      type: "int",
      primary: true,
      generated: true,
      generationStrategy: "increment",
    },
    Territory: {
      type: "varchar",
      length: 255,
      nullable: false,
    },
    PostCode: {
      type: "varchar",
      length: 255,
      nullable: false,
    },
    East: {
      type: "int",
      nullable: false,
    },
    North: {
      type: "int",
      nullable: false,
    },
    Altitude: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinJan: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinFeb: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinMar: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinApr: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinMay: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinJun: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinJul: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinAug: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinSep: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinOct: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinNov: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMinDec: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxJan: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxFeb: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxMar: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxApr: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxMay: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxJun: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxJul: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxAug: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxSep: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxOct: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxNov: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanMaxDec: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallJan: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallFeb: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallMar: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallApr: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallMay: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallJun: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallJul: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallAug: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallSep: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallOct: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallNov: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanTotalRainFallDec: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursJan: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursFeb: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursMar: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursApr: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursMay: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursJun: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursJul: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursAug: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursSep: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursOct: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursNov: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanSunHoursDec: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysJan: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysFeb: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysMar: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysApr: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysMay: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysJun: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysJul: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysAug: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysSep: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysOct: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysNov: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanRainDaysDec: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedJan: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedFeb: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedMar: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedApr: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedMay: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedJun: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedJul: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedAug: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedSep: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedOct: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedNov: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
    MeanWindSpeedDec: {
      type: "decimal",
      precision: 18,
      scale: 9,
      nullable: false,
    },
  },
});

module.exports = { ClimateDatabaseEntity };
