trigger:
  branches:
    include:
      - main  # Replace with the branch you want to trigger the pipeline on

pool:
  vmImage: 'windows-latest'  # Use 'ubuntu-latest' or 'macOS-latest' if needed

steps:

# Step 1: Install Node.js version
- template: templates/install-node.yml  # Call a template to install Node.js
  parameters:
    nodeVersion: '20.16'  # Specify the Node.js version required for your project

# Step 2: Install dependencies
- template: templates/npm-install.yml  # Call a template to install npm packages

# Step 3: Run Webpack build
- template: templates/webpack-build.yml  # Call a template to run Webpack
  parameters:
    buildCommand: 'npm run build'  # Use the build script defined in your package.json

# Step 4: Optional - Publish artifacts
- template: templates/publish-artifact.yml
  parameters:
    artifactPath: 'dist'  # Adjust 'dist' to match the output directory in your Webpack config
    artifactName: 'webpack-build'