export const mockedFarms = [
  {
    ID: 1,
    Name: 'FarmName1',
    Address1: 'Cambridge University Farm',
    Address2: 'Park Farm',
    Address3: null,
    Address4: null,
    Postcode: 'CB23 8YW',
    CPH: null,
    FarmerName: null,
    BusinessName: null,
    SBI: null,
    STD: '01223',
    Telephone: null,
    Mobile: null,
    Email: null,
    Rainfall: 554,
    TotalFarmArea: 0,
    AverageAltitude: 0,
    RegisteredOrganicProducer: false,
    MetricUnits: true,
    EnglishRules: true,
    NVZFields: 0,
    FieldsAbove300SeaLevel: 0,
  },
  {
    ID: 2,
    Name: 'FarmName2',
    Address1: 'Cambridge University Farm2',
    Address2: null,
    Address3: null,
    Address4: null,
    Postcode: 'SS3 9TJ',
    CPH: null,
    FarmerName: null,
    BusinessName: null,
    SBI: null,
    STD: '01223',
    Telephone: null,
    Mobile: null,
    Email: null,
    Rainfall: 554,
    TotalFarmArea: 0,
    AverageAltitude: 0,
    RegisteredOrganicProducer: false,
    MetricUnits: true,
    EnglishRules: true,
    NVZFields: 0,
    FieldsAbove300SeaLevel: 0,
  },
];
