export const createFarmReqBody: any = {
  Name: 'FarmName1',
  Address1: 'Cambridge University Farm',
  Address2: 'Park Farm',
  Address3: null,
  Address4: null,
  Postcode: 'CB23 8YW',
  CPH: null,
  FarmerName: null,
  OrganisationID: 'b5cf0d74-344a-4106-ab3e-1a97cce6b886',
  BusinessName: null,
  SBI: null,
  STD: '01223',
  Telephone: null,
  Mobile: null,
  Email: null,
  Rainfall: 554,
  TotalFarmArea: 0,
  AverageAltitude: 0,
  RegisteredOrganicProducer: false,
  MetricUnits: true,
  EnglishRules: true,
  NVZFields: 0,
  FieldsAbove300SeaLevel: 0,
};

export const createFarmReqBody2: any = {
  Name: 'FarmName2',
  Address1: 'Cambridge University Farm2',
  Address2: null,
  Address3: null,
  Address4: null,
  Postcode: 'SS3 9TJ',
  CPH: null,
  FarmerName: null,
  BusinessName: null,
  SBI: null,
  STD: '01223',
  Telephone: null,
  Mobile: null,
  Email: null,
  Rainfall: 554,
  TotalFarmArea: 0,
  AverageAltitude: 0,
  RegisteredOrganicProducer: false,
  MetricUnits: true,
  EnglishRules: true,
  NVZFields: 0,
  FieldsAbove300SeaLevel: 0,
  CreatedByID: 2,
  ModifiedByID: 2,
};
