export const FertiliserManures = {
  ManagementPeriodID: 1,
  ApplicationDate: new Date(),
  ApplicationRate: 50,
  Confirm: true,
  N: 10,
  P2O5: 20,
  K2O: 30,
  MgO: 5,
  SO3: 5,
  Na2O: 5,
  NFertAnalysisPercent: 10,
  P2O5FertAnalysisPercent: 20,
  K2OFertAnalysisPercent: 30,
  MgOFertAnalysisPercent: 5,
  SO3FertAnalysisPercent: 5,
  Na2OFertAnalysisPercent: 5,
  Lime: 10,
  NH4N: 15,
  NO3N: 20,
  CreatedOn: new Date(),
  CreatedByID: 1,
  ModifiedOn: new Date(),
  ModifiedByID: 1,
};
