export const createFertiliserManureReqBody: any = {
  ManagementPeriodID: null,
  ApplicationDate: new Date(),
  ApplicationRate: 10,
  Confirm: true,
  N: 1.0,
  P2O5: 1.0,
  K2O: 1.0,
  MgO: 1.0,
  SO3: 1.0,
  Na2O: 1.0,
  NFertAnalysisPercent: 1.0,
  P2O5FertAnalysisPercent: 1.0,
  K2OFertAnalysisPercent: 1.0,
  MgOFertAnalysisPercent: 1.0,
  SO3FertAnalysisPercent: 1.0,
  Na2OFertAnalysisPercent: 1.0,
  Lime: 1.0,
  NH4N: 1.0,
  NO3N: 1.0,
  CreatedByID: null,
  ModifiedByID: null,
  CreatedOn: new Date(),
  ModifiedOn: new Date(),
};
