export const createFieldWithSoilAnalysisAndCropsReqBody: any = {
  Field: {
    SoilTypeID: 0,
    NVZProgrammeID: 0,
    Name: 'field 9',
    LPIDNumber: null,
    NationalGridReference: null,
    OtherReference: null,
    TotalArea: 500,
    CroppedArea: null,
    ManureNonSpreadingArea: null,
    SoilReleasingClay: false,
    IsWithinNVZ: false,
    IsAbove300SeaLevel: false,
    IsActive: true,
    CreatedByID: null,
    ModifiedByID: null,
  },
  SoilAnalysis: {
    Year: 0,
    SulphurDeficient: true,
    Date: new Date(),
    PH: 0,
    PhosphorusMethodologyID: 0,
    Phosphorus: 0,
    PhosphorusIndex: 0,
    Potassium: 0,
    PotassiumIndex: 0,
    Magnesium: 0,
    MagnesiumIndex: 0,
    SoilNitrogenSupply: 0,
    SoilNitrogenSupplyIndex: 0,
    Sodium: 0,
    Lime: 0,
    PhosphorusStatus: null,
    PotassiumAnalysis: null,
    PotassiumStatus: null,
    MagnesiumAnalysis: null,
    MagnesiumStatus: null,
    NitrogenResidueGroup: null,
    Comments: null,
    PreviousID: 0,
    CreatedByID: null,
    ModifiedByID: null,
  },
  Crops: [
    {
      Crop: {
        Year: 2024,
        CropTypeID: 0,
        Variety: null,
        OtherCropName: null,
        CropInfo1: 0,
        CropInfo2: 0,
        SowingDate: new Date(),
        Yield: 0,
        Confirm: true,
        PreviousGrass: 0,
        GrassHistory: 0,
        Comments: null,
        Establishment: 0,
        LivestockType: 0,
        MilkYield: 0,
        ConcentrateUse: 0,
        StockingRate: 0,
        DefoliationSequence: 0,
        GrazingIntensity: 0,
        PreviousID: 0,
        CreatedByID: null,
        ModifiedByID: null,
        FieldType: 1,
      },
      ManagementPeriods: [
        {
          DefoliationID: 0,
          Utilisation1ID: 0,
          Utilisation2ID: 0,
          PloughedDown: new Date(),
          CreatedByID: null,
          ModifiedByID: null,
          CreatedOn: new Date(),
          ModifiedOn: new Date(),
          PreviousID: 0,
        },
      ],
    },
  ],
};

export const createFieldReqBody = {
  FarmID: null,
  SoilTypeID: 2,
  NVZProgrammeID: null,
  Name: 'field 5',
  LPIDNumber: null,
  NationalGridReference: null,
  OtherReference: null,
  TotalArea: 500,
  CroppedArea: null,
  ManureNonSpreadingArea: null,
  SoilReleasingClay: false,
  IsWithinNVZ: false,
  IsAbove300SeaLevel: false,
  IsActive: true,
  CreatedOn: '2024-04-24T07:03:29.840Z',
  CreatedByID: null,
  ModifiedOn: null,
  ModifiedByID: null,
};

export const createFieldReqBody2 = {
  SoilTypeID: 2,
  NVZProgrammeID: null,
  Name: 'Test Field',
  LPIDNumber: null,
  NationalGridReference: null,
  OtherReference: null,
  TotalArea: 500,
  CroppedArea: null,
  ManureNonSpreadingArea: null,
  SoilReleasingClay: false,
  IsWithinNVZ: false,
  IsAbove300SeaLevel: false,
  IsActive: true,
};
