export const mockedFields = [
  {
    ID: 20,
    FarmID: 5,
    SoilTypeID: null,
    NVZProgrammeID: null,
    Name: 'field 9',
    LPIDNumber: null,
    NationalGridReference: null,
    OtherReference: null,
    TotalArea: 500,
    CroppedArea: null,
    ManureNonSpreadingArea: null,
    SoilReleasingClay: false,
    IsWithinNVZ: false,
    IsAbove300SeaLevel: false,
    IsActive: true,
  },
  {
    ID: 19,
    FarmID: 5,
    SoilTypeID: null,
    NVZProgrammeID: null,
    Name: 'field 10',
    LPIDNumber: null,
    NationalGridReference: null,
    OtherReference: null,
    TotalArea: 500,
    CroppedArea: null,
    ManureNonSpreadingArea: null,
    SoilReleasingClay: false,
    IsWithinNVZ: false,
    IsAbove300SeaLevel: false,
    IsActive: true,
  },
  {
    ID: 17,
    FarmID: 5,
    SoilTypeID: null,
    NVZProgrammeID: null,
    Name: 'field 5',
    LPIDNumber: null,
    NationalGridReference: null,
    OtherReference: null,
    TotalArea: 500,
    CroppedArea: null,
    ManureNonSpreadingArea: null,
    SoilReleasingClay: false,
    IsWithinNVZ: false,
    IsAbove300SeaLevel: false,
    IsActive: true,
  },
];
