export const createNutrientRecommendationnReqBody: any = {
  field: {
    fieldType: 1,
    multipleCrops: false,
    arable: [
      {
        cropGroupId: 5,
        cropTypeId: 110,
        cropInfo1Id: 1,
        cropInfo2Id: null,
        sowingDate: '2024-05-08T06:43:43.355Z',
        expectedYield: 200,
      },
    ],
    grassland: {},
    soil: {
      soilTypeId: 2,
      kReleasingClay: false,
      soilAnalyses: [
        {
          soilAnalysisDate: '2024-05-08T06:43:43.355Z',
          soilpH: 7,
          sulphurDeficient: true,
          snsIndexId: 3,
          pIndexId: 4,
          kIndexId: 5,
          mgIndexId: 5,
          snsMethodologyId: 4,
          pMethodologyId: 0,
          kMethodologyId: 4,
          mgMethodologyId: 4,
        },
      ],
    },
    harvestYear: 2024,
    area: 500,
    postcode: 'SS3 9TJ',
    altitude: 80,
    rainfallAverage: 300,
    excessWinterRainfall: 50,
    organicMaterials: [],
    previousCropping: {
      previousGrassId: 0,
      previousCropGroupId: 0,
      previousCropTypeId: 0,
      snsId: 0,
      smnDepth: 0,
      measuredSmn: 0,
    },
    countryId: 1,
  },
  nutrients: {
    nitrogen: true,
    phosphate: true,
    potash: true,
    magnesium: true,
    sodium: true,
    sulphur: true,
    lime: true,
  },
  totals: true,
  referenceValue: '1-2024',
};

export const calculateNutrientOffTakeValueReqBody = {
  cropGroupId: 0,
  cropTypeId: 1,
  cropInfo1Id: 1,
  cropInfo2Id: 3,
  countryId: 2,
  nutrientId: 1,
};

export const createRecommendationReqBody = {
  ManagementPeriodID: null,
  CropN: 0,
  CropP2O5: 0,
  CropK2O: 0,
  CropMgO: 0,
  CropSO3: 25,
  CropNa2O: 0,
  CropLime: null,
  ManureN: null,
  ManureP2O5: null,
  ManureK2O: null,
  ManureMgO: null,
  ManureSO3: null,
  ManureNa2O: null,
  ManureLime: null,
  FertilizerN: null,
  FertilizerP2O5: null,
  FertilizerK2O: null,
  FertilizerMgO: null,
  FertilizerSO3: null,
  FertilizerNa2O: null,
  FertilizerLime: null,
  PH: null,
  SNSIndex: null,
  PIndex: null,
  KIndex: null,
  MgIndex: null,
  SIndex: null,
  NaIndex: null,
  Comments: 'Refrence Value: 14-1029-1-2023\nVersion: 1.0.0.0',
  CreatedOn: '2024-05-16T01:17:05.973Z',
  CreatedByID: null,
  ModifiedOn: null,
  ModifiedByID: null,
  PreviousID: null,
};

export const createRecommendationCommentReqBody = [
  {
    RecommendationID: null,
    Nutrient: 1,
    Comment:
      'Recommended rates are for a 15 cm depth of soil. If there is a requirement in both the 0-15 and 15-30 cm soil layers, then higher rates will be needed. The recommendation for the 15-30 cm layer should be ploughed down before planting.',
    CreatedOn: '2024-05-16T01:17:05.990Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
  {
    RecommendationID: null,
    Nutrient: 2,
    Comment:
      'Recommended rates are for a 15 cm depth of soil. If there is a requirement in both the 0-15 and 15-30 cm soil layers, then higher rates will be needed. The recommendation for the 15-30 cm layer should be ploughed down before planting.',
    CreatedOn: '2024-05-16T01:17:05.996Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
  {
    RecommendationID: null,
    Nutrient: 2,
    Comment:
      'When yields are regularly above 40t/ha maintainence applications of potash may need to be increased by 20 kg K20/ha for every additional 10t/ha in yield.',
    CreatedOn: '2024-05-16T01:17:06.010Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
  {
    RecommendationID: null,
    Nutrient: 3,
    Comment:
      'Recommended rates are for a 15 cm depth of soil. If there is a requirement in both the 0-15 and 15-30 cm soil layers, then higher rates will be needed. The recommendation for the 15-30 cm layer should be ploughed down before planting.',
    CreatedOn: '2024-05-16T01:17:06.016Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
  {
    RecommendationID: null,
    Nutrient: 5,
    Comment:
      'Where sulphur deficiency has been recognised or is expected, apply 15–25 kg/ha SO3.',
    CreatedOn: '2024-05-16T01:17:06.030Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
  {
    RecommendationID: null,
    Nutrient: 6,
    Comment:
      'In stony soils lime rates can be reduced e.g. if stones comprise 20% of the soil volume, reduce lime rate by 20%.',
    CreatedOn: '2024-05-16T01:17:06.040Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
  {
    RecommendationID: null,
    Nutrient: 6,
    Comment:
      'Recommended rates are for a 15 cm depth of soil. If there is a requirement in both the 0-15 and 15-30 cm soil layers, then higher rates will be needed. The recommendation for the 15-30 cm layer should be ploughed down before planting.',
    CreatedOn: '2024-05-16T01:17:06.050Z',
    ModifiedOn: null,
    CreatedByID: null,
    ModifiedByID: null,
    PreviousID: null,
  },
];
